language: go

go:
  - 1.14.x
  - master

dist: bionic
addons:
  apt:
    packages:
    - libleptonica-dev
    - tesseract-ocr
    - tesseract-ocr-eng
    - libtesseract-dev

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "parkertron"
  skip_cleanup: true
  on:
    tags: true
